### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by maganius** [DanielKimmich/contactos-idd#3]
Hola Daniel, me gustaria hacerte una consulta con respecto a un issue que hiciste en backpack::crud, por donde te podria contactar?. gracias

**Comment by DanielKimmich** [comment]
Hola con quien tengo el gusto ? Te dejo mi correo "danielkimmich@hotmail.com"

**Comment by DanielKimmich** [comment]
Se responde por privado la consulta de como usar el campo "repeatable". Se puede ver mas en .\crudContact\app\Models\ContactPerson.php
